<table>
 <tbody>
  <tr>
        <td>id</td>         
        <td>name</td> 
        <td>status</td> 
        <td>description</td> 
        <td>servicelevel</td> 
        <td>customer</td> 
        <td>timetable</td> 
        <td>phone</td> 
        <td>email</td> 
        <td>free1</td>  
        <td>e1_tl</td>
        <td>e1_phone</td>
        <td>e1_mobile</td>
        <td>e1_email1</td>
        <td>e1_email2</td>
        <td>e1_comments</td>
        <td>e2_tl</td>
        <td>e2_phone</td>
        <td>e2_mobile</td>
        <td>e2_email1</td>
        <td>e2_email2</td>
        <td>e2_comments</td>
        <td>e3_tl</td>
        <td>e3_phone</td>
        <td>e3_mobile</td>
        <td>e3_email1</td>
        <td>e3_email2</td>
        <td>e3_comments</td>
        <td>global_comment</td>
        <td>created_at</td>
        <td>updated_at</td>
        <td>created_by</td>
        <td>updated_by</td>
  </tr>
  @foreach($teams as $team)
  <tr>
        <td>{{$team['id']}}</td>         
        <td>{{$team['name']}}</td> 
        <td>{{$team['status']}}</td> 
        <td>{{$team['description']}}</td> 
        <td>{{$team['servicelevel']}}</td> 
        <td>{{$team['customer']}}</td> 
        <td>{{$team['timetable']}}</td> 
        <td>{{$team['phone']}}</td> 
        <td>{{$team['email']}}</td> 
        <td>{{$team['free1']}}</td>  
        <td>{{$team['e1_tl']}}</td>
        <td>{{$team['e1_phone']}}</td>
        <td>{{$team['e1_mobile']}}</td>
        <td>{{$team['e1_email1']}}</td>
        <td>{{$team['e1_email2']}}</td>
        <td>{{$team['e1_comments']}}</td>
        <td>{{$team['e2_tl']}}</td>
        <td>{{$team['e2_phone']}}</td>
        <td>{{$team['e2_mobile']}}</td>
        <td>{{$team['e2_email1']}}</td>
        <td>{{$team['e2_email2']}}</td>
        <td>{{$team['e2_comments']}}</td>
        <td>{{$team['e3_tl']}}</td>
        <td>{{$team['e3_phone']}}</td>
        <td>{{$team['e3_mobile']}}</td>
        <td>{{$team['e3_email1']}}</td>
        <td>{{$team['e3_email2']}}</td>
        <td>{{$team['e3_comments']}}</td>
        <td>{{$team['global_comment']}}</td>
        <td>{{$team['created_at']}}</td>
        <td>{{$team['updated_at']}}</td>
        <td>{{$team['created_by']}}</td>
        <td>{{$team['updated_by']}}</td>
  </tr>
  @endforeach
 </tbody>
</table>

