<table>
 <tbody>
  <tr>
                                <td>id</td>
                                <td>name</td>
                                <td>status</td>
                                <td>description</td>
                                <td>site</td>
                                <td>country_id</td>
                                <td>priority_id</td>
                                <td>responsible</td>
                                <td>responsible_date</td>
                                <td>nbuser</td>
                                <td>key_user</td>
                                <td>constructor</td>
                                <td>documentation</td>
                                <td>imac_services</td>
                                <td>imac_ku</td>
                                <td>imac_rr</td>
                                <td>imac_er</td>
                                <td>support_services</td>
                                <td>support_ku</td>
                                <td>support_rr</td>
                                <td>team_id</td>      
                                <td>level1_more</td>
                                <td>team2_id</td>
                                <td>level2_more</td>
                                <td>team3_id</td>
                                <td>level3_more</td>
                                <td>administration</td>
                                <td>administration_ku</td>
                                <td>administration_rr</td>
                                <td>administration_er</td>
                                <td>operation_order</td>
                                <td>oo_ku</td>
                                <td>oo_rr</td>
                                <td>oo_er</td>
                                <td>license_provisioning</td>
                                <td>license_ku</td>
                                <td>license_rr</td>
                                <td>license_er</td>
                                <td>project</td>
                                <td>project_ku</td>
                                <td>global_comment</td>
                                <td>created_at</td>
                                <td>updated_at</td>
                                <td>created_by</td>
                                <td>updated_by</td>
  </tr>
  @foreach($applications as $application)
  <tr>
                                <td>{{$application['id']}}</td>
                                <td>{{$application['name']}}</td>
                                <td>{{$application['status']}}</td>
                                <td>{{$application['description']}}</td>
                                <td>{{$application['site']}}</td>
                                <td>{{$application['country_id']}}</td>
                                <td>{{$application['priority_id']}}</td>
                                <td>{{$application['responsible']}}</td>
                                <td>{{$application['responsible_date']}}</td>
                                <td>{{$application['nbuser']}}</td>
                                <td>{{$application['key_user']}}</td>
                                <td>{{$application['constructor']}}</td>
                                <td>{{$application['documentation']}}</td>
                                <td>{{$application['imac_services']}}</td>
                                <td>{{$application['imac_ku']}}</td>
                                <td>{{$application['imac_rr']}}</td>
                                <td>{{$application['imac_er']}}</td>
                                <td>{{$application['support_services']}}</td>
                                <td>{{$application['support_ku']}}</td>
                                <td>{{$application['support_rr']}}</td>
                                <td>{{$application['team_id']}}</td>      
                                <td>{{$application['level1_more']}}</td>
                                <td>{{$application['team2_id']}}</td>
                                <td>{{$application['level2_more']}}</td>
                                <td>{{$application['team3_id']}}</td>
                                <td>{{$application['level3_more']}}</td>
                                <td>{{$application['administration']}}</td>
                                <td>{{$application['administration_ku']}}</td>
                                <td>{{$application['administration_rr']}}</td>
                                <td>{{$application['administration_er']}}</td>
                                <td>{{$application['operation_order']}}</td>
                                <td>{{$application['oo_ku']}}</td>
                                <td>{{$application['oo_rr']}}</td>
                                <td>{{$application['oo_er']}}</td>
                                <td>{{$application['license_provisioning']}}</td>
                                <td>{{$application['license_ku']}}</td>
                                <td>{{$application['license_rr']}}</td>
                                <td>{{$application['license_er']}}</td>
                                <td>{{$application['project']}}</td>
                                <td>{{$application['project_ku']}}</td>
                                <td>{{$application['global_comment']}}</td>
                                <td>{{$application['created_at']}}</td>
                                <td>{{$application['updated_at']}}</td>
                                <td>{{$application['created_by']}}</td>
                                <td>{{$application['updated_by']}}</td>

  </tr>
  @endforeach
 </tbody>
</table>