<table>
 <tbody>
  <tr>
                                <td>id</td>
                                <td>name</td>
                                <td>status</td>
                                <td>description</td>
                                <td>site</td>
                                <td>country_id</td>
                                <td>priority_id</td>
                                <td>responsible</td>
                                <td>responsible_date</td>
                                <td>categorization</td>
                                <td>documentation</td>
                                <td>procurement</td>
                                <td>procurement_ku</td>
                                <td>procurement_rr</td>
                                <td>procurement_er</td>
                                <td>imac_services</td>
                                <td>imac_ku</td>
                                <td>imac_rr</td>
                                <td>imac_er</td>
                                <td>support_services</td>
                                <td>support_ku</td>
                                <td>support_rr</td>
                                <td>team_id</td>      
                                <td>level1_more</td>
                                <td>team2_id</td>
                                <td>level2_more</td>
                                <td>team3_id</td>
                                <td>level3_more</td>
                                <td>administration</td>
                                <td>administration_ku</td>
                                <td>administration_rr</td>
                                <td>administration_er</td>
                                <td>operation_order</td>
                                <td>oo_ku</td>
                                <td>oo_rr</td>
                                <td>oo_er</td>
                                <td>small_enhancement</td>
                                <td>sm_ku</td>
                                <td>global_comment</td>
                                <td>created_at</td>
                                <td>updated_at</td>
                                <td>created_by</td>
                                <td>updated_by</td>
  </tr>
  @foreach($assets as $asset)
  <tr>
                                <td>{{$asset['id']}}</td>
                                <td>{{$asset['name']}}</td>
                                <td>{{$asset['status']}}</td>
                                <td>{{$asset['description']}}</td>
                                <td>{{$asset['site']}}</td>
                                <td>{{$asset['country_id']}}</td>
                                <td>{{$asset['priority_id']}}</td>
                                <td>{{$asset['responsible']}}</td>
                                <td>{{$asset['responsible_date']}}</td>
                                <td>{{$asset['categorization']}}</td>
                                <td>{{$asset['documentation']}}</td>
                                <td>{{$asset['procurement']}}</td>
                                <td>{{$asset['procurement_ku']}}</td>
                                <td>{{$asset['procurement_rr']}}</td>
                                <td>{{$asset['procurement_er']}}</td>
                                <td>{{$asset['imac_services']}}</td>
                                <td>{{$asset['imac_ku']}}</td>
                                <td>{{$asset['imac_rr']}}</td>
                                <td>{{$asset['imac_er']}}</td>
                                <td>{{$asset['support_services']}}</td>
                                <td>{{$asset['support_ku']}}</td>
                                <td>{{$asset['support_rr']}}</td>
                                <td>{{$asset['team_id']}}</td>      
                                <td>{{$asset['level1_more']}}</td>
                                <td>{{$asset['team2_id']}}</td>
                                <td>{{$asset['level2_more']}}</td>
                                <td>{{$asset['team3_id']}}</td>
                                <td>{{$asset['level3_more']}}</td>
                                <td>{{$asset['administration']}}</td>
                                <td>{{$asset['administration_ku']}}</td>
                                <td>{{$asset['administration_rr']}}</td>
                                <td>{{$asset['administration_er']}}</td>
                                <td>{{$asset['operation_order']}}</td>
                                <td>{{$asset['oo_ku']}}</td>
                                <td>{{$asset['oo_rr']}}</td>
                                <td>{{$asset['oo_er']}}</td>
                                <td>{{$asset['small_enhancement']}}</td>
                                <td>{{$asset['sm_ku']}}</td> 
                                <td>{{$asset['global_comment']}}</td>
                                <td>{{$asset['created_at']}}</td>
                                <td>{{$asset['updated_at']}}</td>
                                <td>{{$asset['created_by']}}</td>
                                <td>{{$asset['updated_by']}}</td>

  </tr>
  @endforeach
 </tbody>
</table>